### ISSUE TITLE
url completo file

### ISSUE THREAD

**Issue by samuele-mrapps** [MrAPPs-RSM/MrappsBackendBundle#30]
Al momento non credo esista un modo per determinare l'url completo dove prendere un file su MrBackend. Servirebbe considerando che può essere attivato o meno il bundle Amazon e questa logica non la metterei a livello di applicativo Symfony.

**Comment by lucamussoni** [comment]
explain please

**Comment by samuele-mrapps** [comment]
Sarebbe comodo un metodo per ottenere l'url completo passando come parametro un'istanza dell'Entity File che internamente determina se è attivo Amazon S3 (o CDN) o meno e quindi compone l'url corretto puntando al dominio opportuno.
