### ISSUE TITLE
classe MrResponse: aggiungere anche error_code come campo

### ISSUE THREAD

**Issue by lucamussoni** [MrAPPs-RSM/MrappsBackendBundle#38]
default null

**Comment by sensorario** [comment]
Manteniamo il formato 

``` json
{
    "data" : [],
    "success" : true,
    "message" : ""
}
```

e quindi usamo data

``` json
{
    "data" : [
        "error_code": 123
    ],
    "success" : true,
    "message" : ""
}
```

Questo ci da una maggiore uniformità su tutti i messaggi. In ogni caso creerei un nuovo oggetto che estenda MrResponse.

**Comment by sensorario** [comment]
Un altro tema, sarebbe quello di separare i messaggi di MrAPPs in due filoni: quelli positivi e quelli negativi. Abbiamo gia' visto quelli positivi. Quelli negativi potrebbero essere:

``` json
{
    "success" : false,
    "message" : "messaggio di errore"
}
```

``` bash
MrResponse
 ├── ErrorResponse
 └── SuccessResponse
```

MrResponse deve sempre contenere succes e message. Error sara' sempre a false, success sara' sempre a true ma avra' anche un campo data. Che cosa ne pensi?
