### ISSUE TITLE
Mostrare la tendina della lingua solo se sono supportate più lingue

### ISSUE THREAD

**Issue by samuele-mrapps** [MrAPPs-RSM/MrappsBackendBundle#44]
Sarebbe utile un parametro nella configurazione per evitare di mostrare la tendina nei pannelli usati da utenti monolingua e che però vogliono usare la funzionalità multilingua per le traduzioni.

**Comment by lucamussoni** [comment]
sistemata lista lingue (in molte rotte era rimasto array hardcoded it+en) + nascosta la tendina se c'è solo una lingua
