### ISSUE TITLE
Implementare paginazione in table.html.twig basata su query string

### ISSUE THREAD

**Issue by samuele-mrapps** [MrAPPs-RSM/MrappsBackendBundle#46]
Al momento quando si fa back dall'edit, ma anche in generale quando si torna all'elenco nella tabella paginata si ritorna sempre alla prima pagina. Sarebbe da implementare la paginazione con i parametri in query string così non si perde l'ultima pagina consultata.

**Comment by lucamussoni** [comment]
🐤

**Comment by lucamussoni** [comment]
https://github.com/MrAPPs-RSM/MrappsBackendBundle/commit/c4936654f98d3eb53cc2f91ca9b0fc23333f1a03
