### ISSUE TITLE
Files - aggiungere possibilità di rimuovere il file se già caricato in precedenza

### ISSUE THREAD

**Issue by samuele-mrapps** [MrAPPs-RSM/MrappsBackendBundle#50]
Questo miglioramento risolve il task segnalato su Erbozeta:

https://trello.com/c/bDkmgSDx/231-creazione-modifica-prodotto-inserire-tasto-per-rimuovere-la-scheda-pdf-caricata

**Comment by lucamussoni** [comment]
aggiunto pulsante "delete" a tipi "file" e "image"
