### ISSUE TITLE
Form - bloccare salvataggio tramite angular se ci sono operazioni asincrone

### ISSUE THREAD

**Issue by samuele-mrapps** [MrAPPs-RSM/MrappsBackendBundle#51]
Al momento può capitare, specialmente con i file, di salvare nella sezione edit/create senza che i contenuti siano stati caricati completamente. Per ovviare a ciò direi di aggiungere lato angular una property disabled che attiva/disattiva il pulsante in base a certe condizioni.

**Comment by lucamussoni** [comment]
fixato per la gallery, gli altri campi avevano già il controllo
